INSERT INTO produto (id, nome, descricao) VALUES (1, 'Smartphone Galaxy S23', 'Celular de última geração com câmera avançada e design premium.');
INSERT INTO produto (id, nome, descricao) VALUES (2, 'Notebook Dell Inspiron', 'Notebook para uso profissional e pessoal com 16GB RAM.');
INSERT INTO produto (id, nome, descricao) VALUES (3, 'Smart TV LG OLED 55"', 'Televisão com tecnologia OLED e resolução 4K.');
INSERT INTO produto (id, nome, descricao) VALUES (4, 'Fone de Ouvido Sony WH-1000XM5', 'Fone de ouvido com cancelamento de ruído ativo.');
INSERT INTO produto (id, nome, descricao) VALUES (5, 'Teclado Mecânico HyperX', 'Teclado gamer com switches mecânicos e iluminação RGB.');
INSERT INTO produto (id, nome, descricao) VALUES (6, 'Mouse Logitech MX Master 3', 'Mouse ergonômico e sem fio com alta precisão.');
INSERT INTO produto (id, nome, descricao) VALUES (7, 'Cafeteira Nespresso Essenza Mini', 'Máquina de café expresso compacta e eficiente.');
INSERT INTO produto (id, nome, descricao) VALUES (8, 'Smartwatch Apple Watch Series 8', 'Relógio inteligente com monitoramento de saúde.');
INSERT INTO produto (id, nome, descricao) VALUES (9, 'Micro-ondas Panasonic 32L', 'Forno micro-ondas com painel digital e alta potência.');
INSERT INTO produto (id, nome, descricao) VALUES (10, 'Fogão Brastemp 4 bocas', 'Fogão a gás com acendimento automático.');
INSERT INTO produto (id, nome, descricao) VALUES (11, 'Geladeira Electrolux Frost Free', 'Refrigerador com capacidade de 375 litros e tecnologia frost free.');
INSERT INTO produto (id, nome, descricao) VALUES (12, 'Cadeira Gamer DXRacer', 'Cadeira ergonômica para jogos e trabalho.');
INSERT INTO produto (id, nome, descricao) VALUES (13, 'Monitor Samsung 27" 4K', 'Monitor UHD com cores vivas e bordas finas.');
INSERT INTO produto (id, nome, descricao) VALUES (14, 'Soundbar JBL 5.1', 'Sistema de som surround com subwoofer integrado.');
INSERT INTO produto (id, nome, descricao) VALUES (15, 'Câmera Canon EOS Rebel T7', 'Câmera DSLR para iniciantes com lente 18-55mm.');
INSERT INTO produto (id, nome, descricao) VALUES (16, 'Air Fryer Mondial Family', 'Fritadeira elétrica sem óleo para alimentos saudáveis.');
INSERT INTO produto (id, nome, descricao) VALUES (17, 'Liquidificador Oster Pro', 'Liquidificador de alta potência com jarra de vidro.');
INSERT INTO produto (id, nome, descricao) VALUES (18, 'Torradeira Philco Gourmet', 'Torradeira com funções de descongelar e aquecer.');
INSERT INTO produto (id, nome, descricao) VALUES (19, 'Máquina de Lavar Samsung EcoBubble', 'Lavadora de roupas com economia de água e energia.');
INSERT INTO produto (id, nome, descricao) VALUES (20, 'Drone DJI Mini 3', 'Drone compacto com câmera 4K e controle remoto.');
INSERT INTO produto (id, nome, descricao) VALUES (21, 'Smart Speaker Amazon Echo', 'Caixa de som inteligente com Alexa integrada.');
INSERT INTO produto (id, nome, descricao) VALUES (22, 'Kindle Paperwhite', 'Leitor de e-books com tela antirreflexo e iluminação ajustável.');
INSERT INTO produto (id, nome, descricao) VALUES (23, 'Ventilador Arno Silence Force', 'Ventilador silencioso com várias velocidades.');
INSERT INTO produto (id, nome, descricao) VALUES (24, 'Chuveiro Lorenzetti Advanced', 'Chuveiro elétrico com sistema de aquecimento rápido.');
INSERT INTO produto (id, nome, descricao) VALUES (25, 'Colchão Ortobom Confort', 'Colchão de espuma com densidade alta para conforto.');
INSERT INTO produto (id, nome, descricao) VALUES (26, 'Mesa de Escritório Delta', 'Mesa em L com design moderno e espaço para trabalho.');
INSERT INTO produto (id, nome, descricao) VALUES (27, 'Impressora HP DeskJet 2776', 'Impressora multifuncional com conexão Wi-Fi.');
INSERT INTO produto (id, nome, descricao) VALUES (28, 'Apontador Elétrico Staedtler', 'Apontador automático para lápis e cores.');
INSERT INTO produto (id, nome, descricao) VALUES (29, 'Patinete Elétrico Xiaomi', 'Veículo elétrico portátil com alta autonomia.');
INSERT INTO produto (id, nome, descricao) VALUES (30, 'Mochila Samsonite Tectonic', 'Mochila ergonômica com compartimentos para laptop.');
ALTER SEQUENCE produto_seq RESTART WITH 31;
